### ISSUE TITLE
请问有没有演示的demo～

### ISSUE THREAD

**Issue by 2856571872** [chivalrousleonard/PaddleOCR#1]

**Comment by chivalrousleonard** [comment]
你可以直接用AVFoundation的代理事件，例如AVCaptureVideoDataOutputSampleBufferDelegate来获取相机捕获到的sampleBuffer，并通过PaddleOCR的scanText的方法来获取识别结果。
`func captureOutput(_ output: AVCaptureOutput, didOutput sampleBuffer: CMSampleBuffer, from connection: AVCaptureConnection) {
        DispatchQueue.global().async {
            paddleOCR?.scanText(from: sampleBuffer,  complete: { (result) in
            /// 获取到识别结果

        })
        }
    }`
